# Generated by Django 2.1.5 on 2019-03-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190320_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmodule',
            options={},
        ),
        migrations.RemoveField(
            model_name='systemmodule',
            name='customer',
        ),
        migrations.AddField(
            model_name='systemmodule',
            name='customer',
            field=models.ManyToManyField(related_name='systems', to='common.Customer'),
        ),
        migrations.AlterField(
            model_name='systemmodule',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
