# Generated by Django 2.1.5 on 2019-03-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190320_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value1', models.CharField(blank=True, max_length=300, null=True)),
                ('value2', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.AlterModelOptions(
            name='systemmodule',
            options={'ordering': ('name',)},
        ),
    ]
