# Generated by Django 2.1.5 on 2019-03-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20190322_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='value1',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='config',
            name='value2',
        ),
    ]
