# Generated by Django 2.1.5 on 2019-03-07 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suplog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.CharField(blank=True, max_length=20, null=True)),
                ('assignee', models.CharField(blank=True, max_length=30, null=True)),
                ('reporter', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('solution', models.TextField(blank=True, max_length=500, null=True)),
                ('issueType', models.CharField(blank=True, max_length=20, null=True)),
                ('sup_date', models.DateField(blank=True, null=True)),
                ('sup_st_time', models.TimeField(blank=True, null=True)),
                ('sup_ed_time', models.TimeField(blank=True, null=True)),
                ('hours', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('sup_date', 'sup_st_time', 'sup_ed_time'),
            },
        ),
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='suplog',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suplog.SystemModule'),
        ),
    ]
