# Generated by Django 2.1.5 on 2019-03-07 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suplog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suplog.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterModelOptions(
            name='suplog',
            options={'ordering': ('sup_st_time', 'sup_ed_time')},
        ),
        migrations.RemoveField(
            model_name='suplog',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='suplog',
            name='sup_date',
        ),
        migrations.AlterField(
            model_name='suplog',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suplog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suplog',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suplog.Customer'),
        ),
        migrations.AlterField(
            model_name='suplog',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suplog.CustomerStaff'),
        ),
        migrations.AlterField(
            model_name='suplog',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suplog.Status'),
        ),
        migrations.AlterField(
            model_name='suplog',
            name='sup_ed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suplog',
            name='sup_st_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
