# Generated by Django 2.1.5 on 2019-03-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suplog', '0002_auto_20190307_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='suplog',
            name='issueType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suplog.Type'),
        ),
    ]
