# Generated by Django 2.1.5 on 2019-03-13 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suplog', '0004_auto_20190312_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstaff',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Customer'),
        ),
        migrations.AlterField(
            model_name='suplog',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Customer'),
        ),
        migrations.AlterField(
            model_name='suplog',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.SystemModule'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='SystemModule',
        ),
    ]
