# Generated by Django 2.1.5 on 2019-03-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplog', '0005_auto_20190313_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplog',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='suplog',
            name='solution',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
