# Generated by Django 2.1.5 on 2019-03-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('remark', models.TextField(blank=True, max_length=500, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Customer')),
            ],
            options={
                'ordering': ('customer', 'envtype', 'url'),
            },
        ),
        migrations.CreateModel(
            name='Envtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='envitem',
            name='envtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='envs.Envtype'),
        ),
    ]
