# Generated by Django 2.1.5 on 2019-03-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envitem',
            options={'ordering': ('customer', 'envtype', 'name')},
        ),
        migrations.AddField(
            model_name='envitem',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
