# Generated by Django 2.1.5 on 2019-03-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envs', '0002_auto_20190313_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envitem',
            name='remark',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='envitem',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
