# Generated by Django 2.1.5 on 2019-02-19 08:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('effort', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)])),
                ('image1', models.CharField(default='', max_length=100)),
                ('image2', models.CharField(default='', max_length=100)),
                ('image3', models.CharField(default='', max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdowns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sequence', 'ticket', 'function_group', 'create_date'),
            },
        ),
        migrations.CreateModel(
            name='BreakdownCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
                ('customer', models.CharField(default='', max_length=20)),
                ('assignee', models.CharField(default='', max_length=20)),
                ('ticket_no', models.CharField(default='', max_length=20)),
                ('summary', models.TextField(blank=True, max_length=500, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('gn_no', models.CharField(default='', max_length=10)),
                ('jira_id', models.IntegerField()),
            ],
            options={
                'ordering': ('-due_date', 'customer', 'ticket_no'),
            },
        ),
        migrations.AddField(
            model_name='breakdown',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakdown.BreakdownCategory'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='function_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakdown.FunctionGroup'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakdown.Status'),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakdowns', to='breakdown.Ticket'),
        ),
    ]
