# Generated by Django 2.1.5 on 2019-02-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='jira_id',
            field=models.IntegerField(default=0),
        ),
    ]
