# Generated by Django 2.1.5 on 2019-01-23 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0003_ticket_ticket_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='create_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='functiongroup',
            name='create_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='create_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
