# Generated by Django 2.1.5 on 2019-02-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0003_auto_20190220_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='gn_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
