# Generated by Django 2.1.5 on 2019-01-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0004_auto_20190123_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='breakdown',
            name='ticket',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='breakdown.Ticket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='breakdown.Customer'),
            preserve_default=False,
        ),
    ]
