# Generated by Django 2.1.5 on 2019-01-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0005_auto_20190124_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('customer', 'ticket_no')},
        ),
    ]
