# Generated by Django 2.1.5 on 2019-03-07 09:17

import breakdown.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0005_auto_20190220_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=breakdown.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=breakdown.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=breakdown.models.upload_path_handler),
        ),
    ]
