# Generated by Django 2.1.5 on 2019-01-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0005_auto_20190124_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
    ]
