# Generated by Django 2.1.5 on 2019-01-24 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0006_remove_ticket_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='breakdown.Customer'),
            preserve_default=False,
        ),
    ]
