# Generated by Django 2.1.5 on 2019-01-27 14:30

import breakdown.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0006_auto_20190127_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakdown',
            options={'ordering': ('ticket', 'function_group', 'create_date')},
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='status',
            field=models.CharField(default=breakdown.models.TaskStatus(1), max_length=10),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakdown', to='breakdown.Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
