# Generated by Django 2.1.5 on 2019-03-12 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0007_auto_20190312_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdowncategory',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='breakdowncategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='breakdown.BreakdownCategory'),
        ),
    ]
