# Generated by Django 2.1.5 on 2019-03-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0008_auto_20190312_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='in_bk',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='in_fd',
            field=models.BooleanField(default=True),
        ),
    ]
