# Generated by Django 2.1.5 on 2019-03-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0009_auto_20190315_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='effort',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
